pipeline {
  agent any
  environment {
    CREATE_SCHEMA = "true"
    RUN_APP = "false"
    DATABASE_URI = credentials("DATABASE_URI")
  }
  stages {
    stage('Setup') {
      steps {
        sh "bash jenkins/install.sh"
      }
    }
    stage('Create Schema') {
      steps {
        script{
          if (env.CREATE_SCHEMA == "true") {
            sh "bash jenkins/schema.sh"
          }
        }
      }
    }
    // stage('Test') {
    //   steps {
    //     sh "bash jenkins/test.sh"
    //   }
    // }
    stage('Run') {
      steps {
        script{
          if (env.RUN_APP == "true") {
            sh "bash jenkins/run_app.sh"
          }
        }
      }
    }
  }
}
